// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	redis "sms-management/internal/infrastructure/redis"

	mock "github.com/stretchr/testify/mock"
)

// CacheManager is an autogenerated mock type for the CacheManager type
type CacheManager struct {
	mock.Mock
}

// BatchUpsert provides a mock function with given fields: ctx, items
func (_m *CacheManager) BatchUpsert(ctx context.Context, items []redis.CacheUpsertItem) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []redis.CacheUpsertItem) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CacheManager) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, id, ipv4, status, retryCount
func (_m *CacheManager) Upsert(ctx context.Context, id string, ipv4 string, status string, retryCount int) error {
	ret := _m.Called(ctx, id, ipv4, status, retryCount)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) error); ok {
		r0 = rf(ctx, id, ipv4, status, retryCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCacheManager creates a new instance of CacheManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheManager {
	mock := &CacheManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

