// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-management/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "sms-management/internal/repository"

	service "sms-management/internal/service"
)

// MockServerService is an autogenerated mock type for the ServerService type
type MockServerService struct {
	mock.Mock
}

type MockServerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerService) EXPECT() *MockServerService_Expecter {
	return &MockServerService_Expecter{mock: &_m.Mock}
}

// CreateServer provides a mock function with given fields: ctx, input
func (_m *MockServerService) CreateServer(ctx context.Context, input service.CreateServerInput) (*domain.Server, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateServer")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateServerInput) (*domain.Server, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateServerInput) *domain.Server); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.CreateServerInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerService_CreateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServer'
type MockServerService_CreateServer_Call struct {
	*mock.Call
}

// CreateServer is a helper method to define mock.On call
//   - ctx context.Context
//   - input service.CreateServerInput
func (_e *MockServerService_Expecter) CreateServer(ctx interface{}, input interface{}) *MockServerService_CreateServer_Call {
	return &MockServerService_CreateServer_Call{Call: _e.mock.On("CreateServer", ctx, input)}
}

func (_c *MockServerService_CreateServer_Call) Run(run func(ctx context.Context, input service.CreateServerInput)) *MockServerService_CreateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.CreateServerInput))
	})
	return _c
}

func (_c *MockServerService_CreateServer_Call) Return(_a0 *domain.Server, _a1 error) *MockServerService_CreateServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerService_CreateServer_Call) RunAndReturn(run func(context.Context, service.CreateServerInput) (*domain.Server, error)) *MockServerService_CreateServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServer provides a mock function with given fields: ctx, id
func (_m *MockServerService) DeleteServer(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerService_DeleteServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServer'
type MockServerService_DeleteServer_Call struct {
	*mock.Call
}

// DeleteServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockServerService_Expecter) DeleteServer(ctx interface{}, id interface{}) *MockServerService_DeleteServer_Call {
	return &MockServerService_DeleteServer_Call{Call: _e.mock.On("DeleteServer", ctx, id)}
}

func (_c *MockServerService_DeleteServer_Call) Run(run func(ctx context.Context, id string)) *MockServerService_DeleteServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerService_DeleteServer_Call) Return(_a0 error) *MockServerService_DeleteServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerService_DeleteServer_Call) RunAndReturn(run func(context.Context, string) error) *MockServerService_DeleteServer_Call {
	_c.Call.Return(run)
	return _c
}

// ExportServers provides a mock function with given fields: ctx, filter
func (_m *MockServerService) ExportServers(ctx context.Context, filter repository.ServerListFilter) ([]byte, string, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ExportServers")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) ([]byte, string, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) []byte); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ServerListFilter) string); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ServerListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockServerService_ExportServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportServers'
type MockServerService_ExportServers_Call struct {
	*mock.Call
}

// ExportServers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.ServerListFilter
func (_e *MockServerService_Expecter) ExportServers(ctx interface{}, filter interface{}) *MockServerService_ExportServers_Call {
	return &MockServerService_ExportServers_Call{Call: _e.mock.On("ExportServers", ctx, filter)}
}

func (_c *MockServerService_ExportServers_Call) Run(run func(ctx context.Context, filter repository.ServerListFilter)) *MockServerService_ExportServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ServerListFilter))
	})
	return _c
}

func (_c *MockServerService_ExportServers_Call) Return(_a0 []byte, _a1 string, _a2 error) *MockServerService_ExportServers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockServerService_ExportServers_Call) RunAndReturn(run func(context.Context, repository.ServerListFilter) ([]byte, string, error)) *MockServerService_ExportServers_Call {
	_c.Call.Return(run)
	return _c
}

// ImportServers provides a mock function with given fields: ctx, fileBytes
func (_m *MockServerService) ImportServers(ctx context.Context, fileBytes []byte) (*service.ImportResult, error) {
	ret := _m.Called(ctx, fileBytes)

	if len(ret) == 0 {
		panic("no return value specified for ImportServers")
	}

	var r0 *service.ImportResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (*service.ImportResult, error)); ok {
		return rf(ctx, fileBytes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *service.ImportResult); ok {
		r0 = rf(ctx, fileBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ImportResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, fileBytes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerService_ImportServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportServers'
type MockServerService_ImportServers_Call struct {
	*mock.Call
}

// ImportServers is a helper method to define mock.On call
//   - ctx context.Context
//   - fileBytes []byte
func (_e *MockServerService_Expecter) ImportServers(ctx interface{}, fileBytes interface{}) *MockServerService_ImportServers_Call {
	return &MockServerService_ImportServers_Call{Call: _e.mock.On("ImportServers", ctx, fileBytes)}
}

func (_c *MockServerService_ImportServers_Call) Run(run func(ctx context.Context, fileBytes []byte)) *MockServerService_ImportServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *MockServerService_ImportServers_Call) Return(_a0 *service.ImportResult, _a1 error) *MockServerService_ImportServers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerService_ImportServers_Call) RunAndReturn(run func(context.Context, []byte) (*service.ImportResult, error)) *MockServerService_ImportServers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchServers provides a mock function with given fields: ctx, filter
func (_m *MockServerService) SearchServers(ctx context.Context, filter repository.ServerListFilter) ([]*domain.Server, int32, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchServers")
	}

	var r0 []*domain.Server
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) ([]*domain.Server, int32, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) []*domain.Server); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ServerListFilter) int32); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ServerListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockServerService_SearchServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchServers'
type MockServerService_SearchServers_Call struct {
	*mock.Call
}

// SearchServers is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.ServerListFilter
func (_e *MockServerService_Expecter) SearchServers(ctx interface{}, filter interface{}) *MockServerService_SearchServers_Call {
	return &MockServerService_SearchServers_Call{Call: _e.mock.On("SearchServers", ctx, filter)}
}

func (_c *MockServerService_SearchServers_Call) Run(run func(ctx context.Context, filter repository.ServerListFilter)) *MockServerService_SearchServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ServerListFilter))
	})
	return _c
}

func (_c *MockServerService_SearchServers_Call) Return(_a0 []*domain.Server, _a1 int32, _a2 error) *MockServerService_SearchServers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockServerService_SearchServers_Call) RunAndReturn(run func(context.Context, repository.ServerListFilter) ([]*domain.Server, int32, error)) *MockServerService_SearchServers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateServer provides a mock function with given fields: ctx, id, input
func (_m *MockServerService) UpdateServer(ctx context.Context, id string, input service.UpdateServerInput) (*domain.Server, error) {
	ret := _m.Called(ctx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServer")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, service.UpdateServerInput) (*domain.Server, error)); ok {
		return rf(ctx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, service.UpdateServerInput) *domain.Server); ok {
		r0 = rf(ctx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, service.UpdateServerInput) error); ok {
		r1 = rf(ctx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerService_UpdateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateServer'
type MockServerService_UpdateServer_Call struct {
	*mock.Call
}

// UpdateServer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - input service.UpdateServerInput
func (_e *MockServerService_Expecter) UpdateServer(ctx interface{}, id interface{}, input interface{}) *MockServerService_UpdateServer_Call {
	return &MockServerService_UpdateServer_Call{Call: _e.mock.On("UpdateServer", ctx, id, input)}
}

func (_c *MockServerService_UpdateServer_Call) Run(run func(ctx context.Context, id string, input service.UpdateServerInput)) *MockServerService_UpdateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(service.UpdateServerInput))
	})
	return _c
}

func (_c *MockServerService_UpdateServer_Call) Return(_a0 *domain.Server, _a1 error) *MockServerService_UpdateServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerService_UpdateServer_Call) RunAndReturn(run func(context.Context, string, service.UpdateServerInput) (*domain.Server, error)) *MockServerService_UpdateServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerService creates a new instance of MockServerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerService {
	mock := &MockServerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
