// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	domain "sms-identity/internal/modules/identity/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenManager is an autogenerated mock type for the TokenManager type
type MockTokenManager struct {
	mock.Mock
}

type MockTokenManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenManager) EXPECT() *MockTokenManager_Expecter {
	return &MockTokenManager_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function with given fields: userID, roleCode, sessionID
func (_m *MockTokenManager) GenerateAccessToken(userID uint, roleCode domain.RoleCode, sessionID uuid.UUID) (string, error) {
	ret := _m.Called(userID, roleCode, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, domain.RoleCode, uuid.UUID) (string, error)); ok {
		return rf(userID, roleCode, sessionID)
	}
	if rf, ok := ret.Get(0).(func(uint, domain.RoleCode, uuid.UUID) string); ok {
		r0 = rf(userID, roleCode, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint, domain.RoleCode, uuid.UUID) error); ok {
		r1 = rf(userID, roleCode, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenManager_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenManager_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID uint
//   - roleCode domain.RoleCode
//   - sessionID uuid.UUID
func (_e *MockTokenManager_Expecter) GenerateAccessToken(userID interface{}, roleCode interface{}, sessionID interface{}) *MockTokenManager_GenerateAccessToken_Call {
	return &MockTokenManager_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, roleCode, sessionID)}
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Run(run func(userID uint, roleCode domain.RoleCode, sessionID uuid.UUID)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(domain.RoleCode), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) Return(_a0 string, _a1 error) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenManager_GenerateAccessToken_Call) RunAndReturn(run func(uint, domain.RoleCode, uuid.UUID) (string, error)) *MockTokenManager_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function with no fields
func (_m *MockTokenManager) GenerateRefreshToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTokenManager_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenManager_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
func (_e *MockTokenManager_Expecter) GenerateRefreshToken() *MockTokenManager_GenerateRefreshToken_Call {
	return &MockTokenManager_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken")}
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) Run(run func()) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) Return(_a0 string) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenManager_GenerateRefreshToken_Call) RunAndReturn(run func() string) *MockTokenManager_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function with given fields: token
func (_m *MockTokenManager) HashToken(token string) string {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTokenManager_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockTokenManager_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenManager_Expecter) HashToken(token interface{}) *MockTokenManager_HashToken_Call {
	return &MockTokenManager_HashToken_Call{Call: _e.mock.On("HashToken", token)}
}

func (_c *MockTokenManager_HashToken_Call) Run(run func(token string)) *MockTokenManager_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenManager_HashToken_Call) Return(_a0 string) *MockTokenManager_HashToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenManager_HashToken_Call) RunAndReturn(run func(string) string) *MockTokenManager_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenManager creates a new instance of MockTokenManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenManager {
	mock := &MockTokenManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}