// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSessionRevocationStore is an autogenerated mock type for the SessionRevocationStore type
type MockSessionRevocationStore struct {
	mock.Mock
}

type MockSessionRevocationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRevocationStore) EXPECT() *MockSessionRevocationStore_Expecter {
	return &MockSessionRevocationStore_Expecter{mock: &_m.Mock}
}

// MarkRevoked provides a mock function with given fields: ctx, sessionID, expiresAt
func (_m *MockSessionRevocationStore) MarkRevoked(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time) error {
	ret := _m.Called(ctx, sessionID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkRevoked")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, sessionID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionRevocationStore_MarkRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRevoked'
type MockSessionRevocationStore_MarkRevoked_Call struct {
	*mock.Call
}

// MarkRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - expiresAt time.Time
func (_e *MockSessionRevocationStore_Expecter) MarkRevoked(ctx interface{}, sessionID interface{}, expiresAt interface{}) *MockSessionRevocationStore_MarkRevoked_Call {
	return &MockSessionRevocationStore_MarkRevoked_Call{Call: _e.mock.On("MarkRevoked", ctx, sessionID, expiresAt)}
}

func (_c *MockSessionRevocationStore_MarkRevoked_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time)) *MockSessionRevocationStore_MarkRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockSessionRevocationStore_MarkRevoked_Call) Return(_a0 error) *MockSessionRevocationStore_MarkRevoked_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionRevocationStore_MarkRevoked_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockSessionRevocationStore_MarkRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionRevocationStore creates a new instance of MockSessionRevocationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRevocationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRevocationStore {
	mock := &MockSessionRevocationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}