// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReportingService is an autogenerated mock type for the ReportingService type
type MockReportingService struct {
	mock.Mock
}

type MockReportingService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportingService) EXPECT() *MockReportingService_Expecter {
	return &MockReportingService_Expecter{mock: &_m.Mock}
}

// RequestReport provides a mock function with given fields: ctx, email, startDate, endDate
func (_m *MockReportingService) RequestReport(ctx context.Context, email string, startDate string, endDate string) error {
	ret := _m.Called(ctx, email, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for RequestReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, startDate, endDate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportingService_RequestReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestReport'
type MockReportingService_RequestReport_Call struct {
	*mock.Call
}

// RequestReport is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - startDate string
//   - endDate string
func (_e *MockReportingService_Expecter) RequestReport(ctx interface{}, email interface{}, startDate interface{}, endDate interface{}) *MockReportingService_RequestReport_Call {
	return &MockReportingService_RequestReport_Call{Call: _e.mock.On("RequestReport", ctx, email, startDate, endDate)}
}

func (_c *MockReportingService_RequestReport_Call) Run(run func(ctx context.Context, email string, startDate string, endDate string)) *MockReportingService_RequestReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockReportingService_RequestReport_Call) Return(_a0 error) *MockReportingService_RequestReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportingService_RequestReport_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockReportingService_RequestReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportingService creates a new instance of MockReportingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportingService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportingService {
	mock := &MockReportingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
