// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-reporting/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockReportingWorker is an autogenerated mock type for the ReportingWorker type
type MockReportingWorker struct {
	mock.Mock
}

type MockReportingWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportingWorker) EXPECT() *MockReportingWorker_Expecter {
	return &MockReportingWorker_Expecter{mock: &_m.Mock}
}

// EnqueueReport provides a mock function with given fields: req
func (_m *MockReportingWorker) EnqueueReport(req *domain.ReportRequest) {
	_m.Called(req)
}

// MockReportingWorker_EnqueueReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueReport'
type MockReportingWorker_EnqueueReport_Call struct {
	*mock.Call
}

// EnqueueReport is a helper method to define mock.On call
//   - req *domain.ReportRequest
func (_e *MockReportingWorker_Expecter) EnqueueReport(req interface{}) *MockReportingWorker_EnqueueReport_Call {
	return &MockReportingWorker_EnqueueReport_Call{Call: _e.mock.On("EnqueueReport", req)}
}

func (_c *MockReportingWorker_EnqueueReport_Call) Run(run func(req *domain.ReportRequest)) *MockReportingWorker_EnqueueReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*domain.ReportRequest))
	})
	return _c
}

func (_c *MockReportingWorker_EnqueueReport_Call) Return() *MockReportingWorker_EnqueueReport_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReportingWorker_EnqueueReport_Call) RunAndReturn(run func(*domain.ReportRequest)) *MockReportingWorker_EnqueueReport_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockReportingWorker) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockReportingWorker_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockReportingWorker_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReportingWorker_Expecter) Start(ctx interface{}) *MockReportingWorker_Start_Call {
	return &MockReportingWorker_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockReportingWorker_Start_Call) Run(run func(ctx context.Context)) *MockReportingWorker_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReportingWorker_Start_Call) Return() *MockReportingWorker_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReportingWorker_Start_Call) RunAndReturn(run func(context.Context)) *MockReportingWorker_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockReportingWorker) Stop() {
	_m.Called()
}

// MockReportingWorker_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockReportingWorker_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockReportingWorker_Expecter) Stop() *MockReportingWorker_Stop_Call {
	return &MockReportingWorker_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockReportingWorker_Stop_Call) Run(run func()) *MockReportingWorker_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportingWorker_Stop_Call) Return() *MockReportingWorker_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReportingWorker_Stop_Call) RunAndReturn(run func()) *MockReportingWorker_Stop_Call {
	_c.Run(run)
	return _c
}

// NewMockReportingWorker creates a new instance of MockReportingWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportingWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportingWorker {
	mock := &MockReportingWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
