// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockUptimeCalculator is an autogenerated mock type for the UptimeCalculator type
type MockUptimeCalculator struct {
	mock.Mock
}

type MockUptimeCalculator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUptimeCalculator) EXPECT() *MockUptimeCalculator_Expecter {
	return &MockUptimeCalculator_Expecter{mock: &_m.Mock}
}

// CalculateUptime provides a mock function with given fields: ctx, startTime, endTime
func (_m *MockUptimeCalculator) CalculateUptime(ctx context.Context, startTime time.Time, endTime time.Time) (float64, error) {
	ret := _m.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for CalculateUptime")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) (float64, error)); ok {
		return rf(ctx, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) float64); ok {
		r0 = rf(ctx, startTime, endTime)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUptimeCalculator_CalculateUptime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CalculateUptime'
type MockUptimeCalculator_CalculateUptime_Call struct {
	*mock.Call
}

// CalculateUptime is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime time.Time
//   - endTime time.Time
func (_e *MockUptimeCalculator_Expecter) CalculateUptime(ctx interface{}, startTime interface{}, endTime interface{}) *MockUptimeCalculator_CalculateUptime_Call {
	return &MockUptimeCalculator_CalculateUptime_Call{Call: _e.mock.On("CalculateUptime", ctx, startTime, endTime)}
}

func (_c *MockUptimeCalculator_CalculateUptime_Call) Run(run func(ctx context.Context, startTime time.Time, endTime time.Time)) *MockUptimeCalculator_CalculateUptime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockUptimeCalculator_CalculateUptime_Call) Return(_a0 float64, _a1 error) *MockUptimeCalculator_CalculateUptime_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUptimeCalculator_CalculateUptime_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) (float64, error)) *MockUptimeCalculator_CalculateUptime_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUptimeCalculator creates a new instance of MockUptimeCalculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUptimeCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUptimeCalculator {
	mock := &MockUptimeCalculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
