// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReportNotifier is an autogenerated mock type for the ReportNotifier type
type MockReportNotifier struct {
	mock.Mock
}

type MockReportNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportNotifier) EXPECT() *MockReportNotifier_Expecter {
	return &MockReportNotifier_Expecter{mock: &_m.Mock}
}

// SendReportEmail provides a mock function with given fields: ctx, toEmail, subject, htmlBody
func (_m *MockReportNotifier) SendReportEmail(ctx context.Context, toEmail string, subject string, htmlBody string) error {
	ret := _m.Called(ctx, toEmail, subject, htmlBody)

	if len(ret) == 0 {
		panic("no return value specified for SendReportEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, toEmail, subject, htmlBody)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportNotifier_SendReportEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReportEmail'
type MockReportNotifier_SendReportEmail_Call struct {
	*mock.Call
}

// SendReportEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - toEmail string
//   - subject string
//   - htmlBody string
func (_e *MockReportNotifier_Expecter) SendReportEmail(ctx interface{}, toEmail interface{}, subject interface{}, htmlBody interface{}) *MockReportNotifier_SendReportEmail_Call {
	return &MockReportNotifier_SendReportEmail_Call{Call: _e.mock.On("SendReportEmail", ctx, toEmail, subject, htmlBody)}
}

func (_c *MockReportNotifier_SendReportEmail_Call) Run(run func(ctx context.Context, toEmail string, subject string, htmlBody string)) *MockReportNotifier_SendReportEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockReportNotifier_SendReportEmail_Call) Return(_a0 error) *MockReportNotifier_SendReportEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportNotifier_SendReportEmail_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockReportNotifier_SendReportEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportNotifier creates a new instance of MockReportNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportNotifier {
	mock := &MockReportNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
