// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotificationConsumer is an autogenerated mock type for the NotificationConsumer type
type MockNotificationConsumer struct {
	mock.Mock
}

type MockNotificationConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationConsumer) EXPECT() *MockNotificationConsumer_Expecter {
	return &MockNotificationConsumer_Expecter{mock: &_m.Mock}
}

// Start provides a mock function with given fields: ctx
func (_m *MockNotificationConsumer) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockNotificationConsumer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockNotificationConsumer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNotificationConsumer_Expecter) Start(ctx interface{}) *MockNotificationConsumer_Start_Call {
	return &MockNotificationConsumer_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockNotificationConsumer_Start_Call) Run(run func(ctx context.Context)) *MockNotificationConsumer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockNotificationConsumer_Start_Call) Return() *MockNotificationConsumer_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNotificationConsumer_Start_Call) RunAndReturn(run func(context.Context)) *MockNotificationConsumer_Start_Call {
	_c.Run(run)
	return _c
}

// NewMockNotificationConsumer creates a new instance of MockNotificationConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationConsumer {
	mock := &MockNotificationConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
