// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	service "sms-identity/internal/service"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, email, password, ipAddress, userAgent
func (_m *MockAuthService) Login(ctx context.Context, email string, password string, ipAddress string, userAgent string) (*service.LoginResult, error) {
	ret := _m.Called(ctx, email, password, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *service.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*service.LoginResult, error)); ok {
		return rf(ctx, email, password, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *service.LoginResult); ok {
		r0 = rf(ctx, email, password, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, email, password, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - ipAddress string
//   - userAgent string
func (_e *MockAuthService_Expecter) Login(ctx interface{}, email interface{}, password interface{}, ipAddress interface{}, userAgent interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, email, password, ipAddress, userAgent)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, email string, password string, ipAddress string, userAgent string)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(_a0 *service.LoginResult, _a1 error) *MockAuthService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*service.LoginResult, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, sessionIDStr
func (_m *MockAuthService) Logout(ctx context.Context, sessionIDStr string) error {
	ret := _m.Called(ctx, sessionIDStr)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionIDStr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionIDStr string
func (_e *MockAuthService_Expecter) Logout(ctx interface{}, sessionIDStr interface{}) *MockAuthService_Logout_Call {
	return &MockAuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, sessionIDStr)}
}

func (_c *MockAuthService_Logout_Call) Run(run func(ctx context.Context, sessionIDStr string)) *MockAuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Logout_Call) Return(_a0 error) *MockAuthService_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function with given fields: ctx, userID
func (_m *MockAuthService) LogoutAll(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthService_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type MockAuthService_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockAuthService_Expecter) LogoutAll(ctx interface{}, userID interface{}) *MockAuthService_LogoutAll_Call {
	return &MockAuthService_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, userID)}
}

func (_c *MockAuthService_LogoutAll_Call) Run(run func(ctx context.Context, userID uint)) *MockAuthService_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAuthService_LogoutAll_Call) Return(_a0 error) *MockAuthService_LogoutAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthService_LogoutAll_Call) RunAndReturn(run func(context.Context, uint) error) *MockAuthService_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthService) Refresh(ctx context.Context, refreshToken string) (*service.RefreshResult, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *service.RefreshResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.RefreshResult, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.RefreshResult); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.RefreshResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthService_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockAuthService_Refresh_Call {
	return &MockAuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockAuthService_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthService_Refresh_Call) Return(_a0 *service.RefreshResult, _a1 error) *MockAuthService_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthService_Refresh_Call) RunAndReturn(run func(context.Context, string) (*service.RefreshResult, error)) *MockAuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}