// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNotificationSender is an autogenerated mock type for the NotificationSender type
type MockNotificationSender struct {
	mock.Mock
}

type MockNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationSender) EXPECT() *MockNotificationSender_Expecter {
	return &MockNotificationSender_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function with given fields: ctx, to, subject, htmlBody
func (_m *MockNotificationSender) SendEmail(ctx context.Context, to string, subject string, htmlBody string) error {
	ret := _m.Called(ctx, to, subject, htmlBody)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, to, subject, htmlBody)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotificationSender_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MockNotificationSender_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - htmlBody string
func (_e *MockNotificationSender_Expecter) SendEmail(ctx interface{}, to interface{}, subject interface{}, htmlBody interface{}) *MockNotificationSender_SendEmail_Call {
	return &MockNotificationSender_SendEmail_Call{Call: _e.mock.On("SendEmail", ctx, to, subject, htmlBody)}
}

func (_c *MockNotificationSender_SendEmail_Call) Run(run func(ctx context.Context, to string, subject string, htmlBody string)) *MockNotificationSender_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockNotificationSender_SendEmail_Call) Return(_a0 error) *MockNotificationSender_SendEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotificationSender_SendEmail_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockNotificationSender_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationSender creates a new instance of MockNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationSender {
	mock := &MockNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
