// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MonitoringService is an autogenerated mock type for the MonitoringService type
type MonitoringService struct {
	mock.Mock
}

// Evaluate provides a mock function with given fields: ctx, serverID, ip, pingSuccess
func (_m *MonitoringService) Evaluate(ctx context.Context, serverID string, ip string, pingSuccess bool) error {
	ret := _m.Called(ctx, serverID, ip, pingSuccess)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, bool) error); ok {
		r0 = rf(ctx, serverID, ip, pingSuccess)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMonitoringService creates a new instance of MonitoringService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringService {
	mock := &MonitoringService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
