// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-identity/internal/modules/identity/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) Create(ctx context.Context, token *domain.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockRefreshTokenRepository_Create_Call {
	return &MockRefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockRefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) Return(_a0 error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.RefreshToken) error) *MockRefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTokenHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockRefreshTokenRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*domain.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type MockRefreshTokenRepository_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepository_Expecter) FindByTokenHash(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepository_FindByTokenHash_Call {
	return &MockRefreshTokenRepository_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepository_FindByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_FindByTokenHash_Call) Return(_a0 *domain.RefreshToken, _a1 error) *MockRefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_FindByTokenHash_Call) RunAndReturn(run func(context.Context, string) (*domain.RefreshToken, error)) *MockRefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReplacement provides a mock function with given fields: ctx, oldTokenID, newTokenID
func (_m *MockRefreshTokenRepository) MarkReplacement(ctx context.Context, oldTokenID uuid.UUID, newTokenID uuid.UUID) error {
	ret := _m.Called(ctx, oldTokenID, newTokenID)

	if len(ret) == 0 {
		panic("no return value specified for MarkReplacement")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, oldTokenID, newTokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_MarkReplacement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReplacement'
type MockRefreshTokenRepository_MarkReplacement_Call struct {
	*mock.Call
}

// MarkReplacement is a helper method to define mock.On call
//   - ctx context.Context
//   - oldTokenID uuid.UUID
//   - newTokenID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) MarkReplacement(ctx interface{}, oldTokenID interface{}, newTokenID interface{}) *MockRefreshTokenRepository_MarkReplacement_Call {
	return &MockRefreshTokenRepository_MarkReplacement_Call{Call: _e.mock.On("MarkReplacement", ctx, oldTokenID, newTokenID)}
}

func (_c *MockRefreshTokenRepository_MarkReplacement_Call) Run(run func(ctx context.Context, oldTokenID uuid.UUID, newTokenID uuid.UUID)) *MockRefreshTokenRepository_MarkReplacement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_MarkReplacement_Call) Return(_a0 error) *MockRefreshTokenRepository_MarkReplacement_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_MarkReplacement_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockRefreshTokenRepository_MarkReplacement_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function with given fields: ctx, id
func (_m *MockRefreshTokenRepository) RevokeByID(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type MockRefreshTokenRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) RevokeByID(ctx interface{}, id interface{}) *MockRefreshTokenRepository_RevokeByID_Call {
	return &MockRefreshTokenRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *MockRefreshTokenRepository_RevokeByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByID_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeBySessionID provides a mock function with given fields: ctx, sessionID
func (_m *MockRefreshTokenRepository) RevokeBySessionID(ctx context.Context, sessionID uuid.UUID) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeBySessionID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeBySessionID'
type MockRefreshTokenRepository_RevokeBySessionID_Call struct {
	*mock.Call
}

// RevokeBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockRefreshTokenRepository_Expecter) RevokeBySessionID(ctx interface{}, sessionID interface{}) *MockRefreshTokenRepository_RevokeBySessionID_Call {
	return &MockRefreshTokenRepository_RevokeBySessionID_Call{Call: _e.mock.On("RevokeBySessionID", ctx, sessionID)}
}

func (_c *MockRefreshTokenRepository_RevokeBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockRefreshTokenRepository_RevokeBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeBySessionID_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeBySessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeBySessionID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRefreshTokenRepository_RevokeBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByUserID provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) RevokeByUserID(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByUserID'
type MockRefreshTokenRepository_RevokeByUserID_Call struct {
	*mock.Call
}

// RevokeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockRefreshTokenRepository_Expecter) RevokeByUserID(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_RevokeByUserID_Call {
	return &MockRefreshTokenRepository_RevokeByUserID_Call{Call: _e.mock.On("RevokeByUserID", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_RevokeByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockRefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByUserID_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeByUserID_Call) RunAndReturn(run func(context.Context, uint) error) *MockRefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}