// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-identity/internal/modules/identity/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAuthSessionRepository is an autogenerated mock type for the AuthSessionRepository type
type MockAuthSessionRepository struct {
	mock.Mock
}

type MockAuthSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthSessionRepository) EXPECT() *MockAuthSessionRepository_Expecter {
	return &MockAuthSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, session
func (_m *MockAuthSessionRepository) Create(ctx context.Context, session *domain.AuthSession) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AuthSession) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAuthSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.AuthSession
func (_e *MockAuthSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *MockAuthSessionRepository_Create_Call {
	return &MockAuthSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockAuthSessionRepository_Create_Call) Run(run func(ctx context.Context, session *domain.AuthSession)) *MockAuthSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.AuthSession))
	})
	return _c
}

func (_c *MockAuthSessionRepository_Create_Call) Return(_a0 error) *MockAuthSessionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthSessionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.AuthSession) error) *MockAuthSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByID provides a mock function with given fields: ctx, id
func (_m *MockAuthSessionRepository) FindActiveByID(ctx context.Context, id uuid.UUID) (*domain.AuthSession, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByID")
	}

	var r0 *domain.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.AuthSession, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.AuthSession); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthSessionRepository_FindActiveByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByID'
type MockAuthSessionRepository_FindActiveByID_Call struct {
	*mock.Call
}

// FindActiveByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthSessionRepository_Expecter) FindActiveByID(ctx interface{}, id interface{}) *MockAuthSessionRepository_FindActiveByID_Call {
	return &MockAuthSessionRepository_FindActiveByID_Call{Call: _e.mock.On("FindActiveByID", ctx, id)}
}

func (_c *MockAuthSessionRepository_FindActiveByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthSessionRepository_FindActiveByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthSessionRepository_FindActiveByID_Call) Return(_a0 *domain.AuthSession, _a1 error) *MockAuthSessionRepository_FindActiveByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthSessionRepository_FindActiveByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.AuthSession, error)) *MockAuthSessionRepository_FindActiveByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAuthSessionRepository) ListActiveByUserID(ctx context.Context, userID uint) ([]*domain.AuthSession, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByUserID")
	}

	var r0 []*domain.AuthSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]*domain.AuthSession, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []*domain.AuthSession); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.AuthSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthSessionRepository_ListActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByUserID'
type MockAuthSessionRepository_ListActiveByUserID_Call struct {
	*mock.Call
}

// ListActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockAuthSessionRepository_Expecter) ListActiveByUserID(ctx interface{}, userID interface{}) *MockAuthSessionRepository_ListActiveByUserID_Call {
	return &MockAuthSessionRepository_ListActiveByUserID_Call{Call: _e.mock.On("ListActiveByUserID", ctx, userID)}
}

func (_c *MockAuthSessionRepository_ListActiveByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockAuthSessionRepository_ListActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAuthSessionRepository_ListActiveByUserID_Call) Return(_a0 []*domain.AuthSession, _a1 error) *MockAuthSessionRepository_ListActiveByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthSessionRepository_ListActiveByUserID_Call) RunAndReturn(run func(context.Context, uint) ([]*domain.AuthSession, error)) *MockAuthSessionRepository_ListActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAuthSessionRepository) RevokeAllByUserID(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthSessionRepository_RevokeAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUserID'
type MockAuthSessionRepository_RevokeAllByUserID_Call struct {
	*mock.Call
}

// RevokeAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockAuthSessionRepository_Expecter) RevokeAllByUserID(ctx interface{}, userID interface{}) *MockAuthSessionRepository_RevokeAllByUserID_Call {
	return &MockAuthSessionRepository_RevokeAllByUserID_Call{Call: _e.mock.On("RevokeAllByUserID", ctx, userID)}
}

func (_c *MockAuthSessionRepository_RevokeAllByUserID_Call) Run(run func(ctx context.Context, userID uint)) *MockAuthSessionRepository_RevokeAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockAuthSessionRepository_RevokeAllByUserID_Call) Return(_a0 error) *MockAuthSessionRepository_RevokeAllByUserID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthSessionRepository_RevokeAllByUserID_Call) RunAndReturn(run func(context.Context, uint) error) *MockAuthSessionRepository_RevokeAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function with given fields: ctx, id
func (_m *MockAuthSessionRepository) RevokeByID(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthSessionRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type MockAuthSessionRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAuthSessionRepository_Expecter) RevokeByID(ctx interface{}, id interface{}) *MockAuthSessionRepository_RevokeByID_Call {
	return &MockAuthSessionRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *MockAuthSessionRepository_RevokeByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAuthSessionRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAuthSessionRepository_RevokeByID_Call) Return(_a0 error) *MockAuthSessionRepository_RevokeByID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthSessionRepository_RevokeByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAuthSessionRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthSessionRepository creates a new instance of MockAuthSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthSessionRepository {
	mock := &MockAuthSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}