// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-monitoring/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockServerStateStore is an autogenerated mock type for the ServerStateStore type
type MockServerStateStore struct {
	mock.Mock
}

type MockServerStateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerStateStore) EXPECT() *MockServerStateStore_Expecter {
	return &MockServerStateStore_Expecter{mock: &_m.Mock}
}

// GetServerState provides a mock function with given fields: ctx, serverID
func (_m *MockServerStateStore) GetServerState(ctx context.Context, serverID string) (*domain.ServerState, error) {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for GetServerState")
	}

	var r0 *domain.ServerState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.ServerState, error)); ok {
		return rf(ctx, serverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ServerState); ok {
		r0 = rf(ctx, serverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ServerState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerStateStore_GetServerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerState'
type MockServerStateStore_GetServerState_Call struct {
	*mock.Call
}

// GetServerState is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
func (_e *MockServerStateStore_Expecter) GetServerState(ctx interface{}, serverID interface{}) *MockServerStateStore_GetServerState_Call {
	return &MockServerStateStore_GetServerState_Call{Call: _e.mock.On("GetServerState", ctx, serverID)}
}

func (_c *MockServerStateStore_GetServerState_Call) Run(run func(ctx context.Context, serverID string)) *MockServerStateStore_GetServerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerStateStore_GetServerState_Call) Return(_a0 *domain.ServerState, _a1 error) *MockServerStateStore_GetServerState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerStateStore_GetServerState_Call) RunAndReturn(run func(context.Context, string) (*domain.ServerState, error)) *MockServerStateStore_GetServerState_Call {
	_c.Call.Return(run)
	return _c
}

// SetServerState provides a mock function with given fields: ctx, serverID, status, retryCount
func (_m *MockServerStateStore) SetServerState(ctx context.Context, serverID string, status string, retryCount int) error {
	ret := _m.Called(ctx, serverID, status, retryCount)

	if len(ret) == 0 {
		panic("no return value specified for SetServerState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, serverID, status, retryCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerStateStore_SetServerState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServerState'
type MockServerStateStore_SetServerState_Call struct {
	*mock.Call
}

// SetServerState is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - status string
//   - retryCount int
func (_e *MockServerStateStore_Expecter) SetServerState(ctx interface{}, serverID interface{}, status interface{}, retryCount interface{}) *MockServerStateStore_SetServerState_Call {
	return &MockServerStateStore_SetServerState_Call{Call: _e.mock.On("SetServerState", ctx, serverID, status, retryCount)}
}

func (_c *MockServerStateStore_SetServerState_Call) Run(run func(ctx context.Context, serverID string, status string, retryCount int)) *MockServerStateStore_SetServerState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockServerStateStore_SetServerState_Call) Return(_a0 error) *MockServerStateStore_SetServerState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerStateStore_SetServerState_Call) RunAndReturn(run func(context.Context, string, string, int) error) *MockServerStateStore_SetServerState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerStateStore creates a new instance of MockServerStateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerStateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerStateStore {
	mock := &MockServerStateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
