// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ObservationLogger is an autogenerated mock type for the ObservationLogger type
type ObservationLogger struct {
	mock.Mock
}

// LogObservation provides a mock function with given fields: ctx, serverID, isSuccess
func (_m *ObservationLogger) LogObservation(ctx context.Context, serverID string, isSuccess bool) {
	_m.Called(ctx, serverID, isSuccess)
}

// Shutdown provides a mock function with no fields
func (_m *ObservationLogger) Shutdown() {
	_m.Called()
}

// NewObservationLogger creates a new instance of ObservationLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObservationLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObservationLogger {
	mock := &ObservationLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
