// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-management/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "sms-management/internal/repository"
)

// MockServerRepository is an autogenerated mock type for the ServerRepository type
type MockServerRepository struct {
	mock.Mock
}

type MockServerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerRepository) EXPECT() *MockServerRepository_Expecter {
	return &MockServerRepository_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function with given fields: ctx, servers
func (_m *MockServerRepository) BatchCreate(ctx context.Context, servers []*domain.Server) error {
	ret := _m.Called(ctx, servers)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Server) error); ok {
		r0 = rf(ctx, servers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type MockServerRepository_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - servers []*domain.Server
func (_e *MockServerRepository_Expecter) BatchCreate(ctx interface{}, servers interface{}) *MockServerRepository_BatchCreate_Call {
	return &MockServerRepository_BatchCreate_Call{Call: _e.mock.On("BatchCreate", ctx, servers)}
}

func (_c *MockServerRepository_BatchCreate_Call) Run(run func(ctx context.Context, servers []*domain.Server)) *MockServerRepository_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.Server))
	})
	return _c
}

func (_c *MockServerRepository_BatchCreate_Call) Return(_a0 error) *MockServerRepository_BatchCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_BatchCreate_Call) RunAndReturn(run func(context.Context, []*domain.Server) error) *MockServerRepository_BatchCreate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, server
func (_m *MockServerRepository) Create(ctx context.Context, server *domain.Server) error {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server) error); ok {
		r0 = rf(ctx, server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServerRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - server *domain.Server
func (_e *MockServerRepository_Expecter) Create(ctx interface{}, server interface{}) *MockServerRepository_Create_Call {
	return &MockServerRepository_Create_Call{Call: _e.mock.On("Create", ctx, server)}
}

func (_c *MockServerRepository_Create_Call) Run(run func(ctx context.Context, server *domain.Server)) *MockServerRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Server))
	})
	return _c
}

func (_c *MockServerRepository_Create_Call) Return(_a0 error) *MockServerRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Server) error) *MockServerRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockServerRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockServerRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockServerRepository_Delete_Call {
	return &MockServerRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockServerRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockServerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerRepository_Delete_Call) Return(_a0 error) *MockServerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockServerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByNamesOrIPv4s provides a mock function with given fields: ctx, names, ipv4s
func (_m *MockServerRepository) FindByNamesOrIPv4s(ctx context.Context, names []string, ipv4s []string) ([]*domain.Server, error) {
	ret := _m.Called(ctx, names, ipv4s)

	if len(ret) == 0 {
		panic("no return value specified for FindByNamesOrIPv4s")
	}

	var r0 []*domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) ([]*domain.Server, error)); ok {
		return rf(ctx, names, ipv4s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) []*domain.Server); ok {
		r0 = rf(ctx, names, ipv4s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = rf(ctx, names, ipv4s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepository_FindByNamesOrIPv4s_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNamesOrIPv4s'
type MockServerRepository_FindByNamesOrIPv4s_Call struct {
	*mock.Call
}

// FindByNamesOrIPv4s is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
//   - ipv4s []string
func (_e *MockServerRepository_Expecter) FindByNamesOrIPv4s(ctx interface{}, names interface{}, ipv4s interface{}) *MockServerRepository_FindByNamesOrIPv4s_Call {
	return &MockServerRepository_FindByNamesOrIPv4s_Call{Call: _e.mock.On("FindByNamesOrIPv4s", ctx, names, ipv4s)}
}

func (_c *MockServerRepository_FindByNamesOrIPv4s_Call) Run(run func(ctx context.Context, names []string, ipv4s []string)) *MockServerRepository_FindByNamesOrIPv4s_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]string))
	})
	return _c
}

func (_c *MockServerRepository_FindByNamesOrIPv4s_Call) Return(_a0 []*domain.Server, _a1 error) *MockServerRepository_FindByNamesOrIPv4s_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepository_FindByNamesOrIPv4s_Call) RunAndReturn(run func(context.Context, []string, []string) ([]*domain.Server, error)) *MockServerRepository_FindByNamesOrIPv4s_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockServerRepository) GetByID(ctx context.Context, id string) (*domain.Server, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Server, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Server); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockServerRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockServerRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockServerRepository_GetByID_Call {
	return &MockServerRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockServerRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockServerRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerRepository_GetByID_Call) Return(_a0 *domain.Server, _a1 error) *MockServerRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Server, error)) *MockServerRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIPv4 provides a mock function with given fields: ctx, ipv4
func (_m *MockServerRepository) GetByIPv4(ctx context.Context, ipv4 string) (*domain.Server, error) {
	ret := _m.Called(ctx, ipv4)

	if len(ret) == 0 {
		panic("no return value specified for GetByIPv4")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Server, error)); ok {
		return rf(ctx, ipv4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Server); ok {
		r0 = rf(ctx, ipv4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ipv4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepository_GetByIPv4_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIPv4'
type MockServerRepository_GetByIPv4_Call struct {
	*mock.Call
}

// GetByIPv4 is a helper method to define mock.On call
//   - ctx context.Context
//   - ipv4 string
func (_e *MockServerRepository_Expecter) GetByIPv4(ctx interface{}, ipv4 interface{}) *MockServerRepository_GetByIPv4_Call {
	return &MockServerRepository_GetByIPv4_Call{Call: _e.mock.On("GetByIPv4", ctx, ipv4)}
}

func (_c *MockServerRepository_GetByIPv4_Call) Run(run func(ctx context.Context, ipv4 string)) *MockServerRepository_GetByIPv4_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerRepository_GetByIPv4_Call) Return(_a0 *domain.Server, _a1 error) *MockServerRepository_GetByIPv4_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepository_GetByIPv4_Call) RunAndReturn(run func(context.Context, string) (*domain.Server, error)) *MockServerRepository_GetByIPv4_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockServerRepository) GetByName(ctx context.Context, name string) (*domain.Server, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Server, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Server); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockServerRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockServerRepository_Expecter) GetByName(ctx interface{}, name interface{}) *MockServerRepository_GetByName_Call {
	return &MockServerRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockServerRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockServerRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerRepository_GetByName_Call) Return(_a0 *domain.Server, _a1 error) *MockServerRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Server, error)) *MockServerRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function with given fields: ctx, filter
func (_m *MockServerRepository) Search(ctx context.Context, filter repository.ServerListFilter) ([]*domain.Server, int32, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Server
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) ([]*domain.Server, int32, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) []*domain.Server); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ServerListFilter) int32); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ServerListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockServerRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockServerRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filter repository.ServerListFilter
func (_e *MockServerRepository_Expecter) Search(ctx interface{}, filter interface{}) *MockServerRepository_Search_Call {
	return &MockServerRepository_Search_Call{Call: _e.mock.On("Search", ctx, filter)}
}

func (_c *MockServerRepository_Search_Call) Run(run func(ctx context.Context, filter repository.ServerListFilter)) *MockServerRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.ServerListFilter))
	})
	return _c
}

func (_c *MockServerRepository_Search_Call) Return(_a0 []*domain.Server, _a1 int32, _a2 error) *MockServerRepository_Search_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockServerRepository_Search_Call) RunAndReturn(run func(context.Context, repository.ServerListFilter) ([]*domain.Server, int32, error)) *MockServerRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, server
func (_m *MockServerRepository) Update(ctx context.Context, server *domain.Server) error {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server) error); ok {
		r0 = rf(ctx, server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - server *domain.Server
func (_e *MockServerRepository_Expecter) Update(ctx interface{}, server interface{}) *MockServerRepository_Update_Call {
	return &MockServerRepository_Update_Call{Call: _e.mock.On("Update", ctx, server)}
}

func (_c *MockServerRepository_Update_Call) Run(run func(ctx context.Context, server *domain.Server)) *MockServerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Server))
	})
	return _c
}

func (_c *MockServerRepository_Update_Call) Return(_a0 error) *MockServerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Server) error) *MockServerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerRepository creates a new instance of MockServerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerRepository {
	mock := &MockServerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
