// Code generated by mockery v2.53.6. DO NOT EDIT.

package repomock

import (
	context "context"
	domain "sms-management/internal/domain"

	mock "github.com/stretchr/testify/mock"

	repository "sms-management/internal/repository"
)

// ServerRepository is an autogenerated mock type for the ServerRepository type
type ServerRepository struct {
	mock.Mock
}

// BatchCreate provides a mock function with given fields: ctx, servers
func (_m *ServerRepository) BatchCreate(ctx context.Context, servers []*domain.Server) error {
	ret := _m.Called(ctx, servers)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Server) error); ok {
		r0 = rf(ctx, servers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, server
func (_m *ServerRepository) Create(ctx context.Context, server *domain.Server) error {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server) error); ok {
		r0 = rf(ctx, server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ServerRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExecuteInTx provides a mock function with given fields: ctx, fn
func (_m *ServerRepository) ExecuteInTx(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByNamesOrIPv4s provides a mock function with given fields: ctx, names, ipv4s
func (_m *ServerRepository) FindByNamesOrIPv4s(ctx context.Context, names []string, ipv4s []string) ([]*domain.Server, error) {
	ret := _m.Called(ctx, names, ipv4s)

	if len(ret) == 0 {
		panic("no return value specified for FindByNamesOrIPv4s")
	}

	var r0 []*domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) ([]*domain.Server, error)); ok {
		return rf(ctx, names, ipv4s)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) []*domain.Server); ok {
		r0 = rf(ctx, names, ipv4s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = rf(ctx, names, ipv4s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ServerRepository) GetByID(ctx context.Context, id string) (*domain.Server, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Server, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Server); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIPv4 provides a mock function with given fields: ctx, ipv4
func (_m *ServerRepository) GetByIPv4(ctx context.Context, ipv4 string) (*domain.Server, error) {
	ret := _m.Called(ctx, ipv4)

	if len(ret) == 0 {
		panic("no return value specified for GetByIPv4")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Server, error)); ok {
		return rf(ctx, ipv4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Server); ok {
		r0 = rf(ctx, ipv4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ipv4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *ServerRepository) GetByName(ctx context.Context, name string) (*domain.Server, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Server, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Server); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, filter
func (_m *ServerRepository) Search(ctx context.Context, filter repository.ServerListFilter) ([]*domain.Server, int32, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*domain.Server
	var r1 int32
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) ([]*domain.Server, int32, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.ServerListFilter) []*domain.Server); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.ServerListFilter) int32); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int32)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.ServerListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, server
func (_m *ServerRepository) Update(ctx context.Context, server *domain.Server) error {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Server) error); ok {
		r0 = rf(ctx, server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewServerRepository creates a new instance of ServerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerRepository {
	mock := &ServerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
