// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-management/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockOutboxRepository is an autogenerated mock type for the OutboxRepository type
type MockOutboxRepository struct {
	mock.Mock
}

type MockOutboxRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepository) EXPECT() *MockOutboxRepository_Expecter {
	return &MockOutboxRepository_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function with given fields: ctx, events
func (_m *MockOutboxRepository) BatchCreate(ctx context.Context, events []*domain.OutboxEvent) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.OutboxEvent) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type MockOutboxRepository_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - events []*domain.OutboxEvent
func (_e *MockOutboxRepository_Expecter) BatchCreate(ctx interface{}, events interface{}) *MockOutboxRepository_BatchCreate_Call {
	return &MockOutboxRepository_BatchCreate_Call{Call: _e.mock.On("BatchCreate", ctx, events)}
}

func (_c *MockOutboxRepository_BatchCreate_Call) Run(run func(ctx context.Context, events []*domain.OutboxEvent)) *MockOutboxRepository_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.OutboxEvent))
	})
	return _c
}

func (_c *MockOutboxRepository_BatchCreate_Call) Return(_a0 error) *MockOutboxRepository_BatchCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_BatchCreate_Call) RunAndReturn(run func(context.Context, []*domain.OutboxEvent) error) *MockOutboxRepository_BatchCreate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, event
func (_m *MockOutboxRepository) Create(ctx context.Context, event *domain.OutboxEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OutboxEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOutboxRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *domain.OutboxEvent
func (_e *MockOutboxRepository_Expecter) Create(ctx interface{}, event interface{}) *MockOutboxRepository_Create_Call {
	return &MockOutboxRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockOutboxRepository_Create_Call) Run(run func(ctx context.Context, event *domain.OutboxEvent)) *MockOutboxRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.OutboxEvent))
	})
	return _c
}

func (_c *MockOutboxRepository_Create_Call) Return(_a0 error) *MockOutboxRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.OutboxEvent) error) *MockOutboxRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnprocessed provides a mock function with given fields: ctx, limit
func (_m *MockOutboxRepository) GetUnprocessed(ctx context.Context, limit int) ([]*domain.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetUnprocessed")
	}

	var r0 []*domain.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepository_GetUnprocessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnprocessed'
type MockOutboxRepository_GetUnprocessed_Call struct {
	*mock.Call
}

// GetUnprocessed is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxRepository_Expecter) GetUnprocessed(ctx interface{}, limit interface{}) *MockOutboxRepository_GetUnprocessed_Call {
	return &MockOutboxRepository_GetUnprocessed_Call{Call: _e.mock.On("GetUnprocessed", ctx, limit)}
}

func (_c *MockOutboxRepository_GetUnprocessed_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxRepository_GetUnprocessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOutboxRepository_GetUnprocessed_Call) Return(_a0 []*domain.OutboxEvent, _a1 error) *MockOutboxRepository_GetUnprocessed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepository_GetUnprocessed_Call) RunAndReturn(run func(context.Context, int) ([]*domain.OutboxEvent, error)) *MockOutboxRepository_GetUnprocessed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkProcessed provides a mock function with given fields: ctx, ids
func (_m *MockOutboxRepository) MarkProcessed(ctx context.Context, ids []string) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MarkProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepository_MarkProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkProcessed'
type MockOutboxRepository_MarkProcessed_Call struct {
	*mock.Call
}

// MarkProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockOutboxRepository_Expecter) MarkProcessed(ctx interface{}, ids interface{}) *MockOutboxRepository_MarkProcessed_Call {
	return &MockOutboxRepository_MarkProcessed_Call{Call: _e.mock.On("MarkProcessed", ctx, ids)}
}

func (_c *MockOutboxRepository_MarkProcessed_Call) Run(run func(ctx context.Context, ids []string)) *MockOutboxRepository_MarkProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockOutboxRepository_MarkProcessed_Call) Return(_a0 error) *MockOutboxRepository_MarkProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepository_MarkProcessed_Call) RunAndReturn(run func(context.Context, []string) error) *MockOutboxRepository_MarkProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepository creates a new instance of MockOutboxRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepository {
	mock := &MockOutboxRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
