// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-management/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// PublishOutboxBatch provides a mock function with given fields: ctx, stream, events
func (_m *MockPublisher) PublishOutboxBatch(ctx context.Context, stream string, events []*domain.OutboxEvent) error {
	ret := _m.Called(ctx, stream, events)

	if len(ret) == 0 {
		panic("no return value specified for PublishOutboxBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*domain.OutboxEvent) error); ok {
		r0 = rf(ctx, stream, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishOutboxBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOutboxBatch'
type MockPublisher_PublishOutboxBatch_Call struct {
	*mock.Call
}

// PublishOutboxBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - stream string
//   - events []*domain.OutboxEvent
func (_e *MockPublisher_Expecter) PublishOutboxBatch(ctx interface{}, stream interface{}, events interface{}) *MockPublisher_PublishOutboxBatch_Call {
	return &MockPublisher_PublishOutboxBatch_Call{Call: _e.mock.On("PublishOutboxBatch", ctx, stream, events)}
}

func (_c *MockPublisher_PublishOutboxBatch_Call) Run(run func(ctx context.Context, stream string, events []*domain.OutboxEvent)) *MockPublisher_PublishOutboxBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]*domain.OutboxEvent))
	})
	return _c
}

func (_c *MockPublisher_PublishOutboxBatch_Call) Return(_a0 error) *MockPublisher_PublishOutboxBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishOutboxBatch_Call) RunAndReturn(run func(context.Context, string, []*domain.OutboxEvent) error) *MockPublisher_PublishOutboxBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
