// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockPinger is an autogenerated mock type for the Pinger type
type MockPinger struct {
	mock.Mock
}

type MockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinger) EXPECT() *MockPinger_Expecter {
	return &MockPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ip, timeout
func (_m *MockPinger) Ping(ip string, timeout time.Duration) bool {
	ret := _m.Called(ip, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, time.Duration) bool); ok {
		r0 = rf(ip, timeout)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ip string
//   - timeout time.Duration
func (_e *MockPinger_Expecter) Ping(ip interface{}, timeout interface{}) *MockPinger_Ping_Call {
	return &MockPinger_Ping_Call{Call: _e.mock.On("Ping", ip, timeout)}
}

func (_c *MockPinger_Ping_Call) Run(run func(ip string, timeout time.Duration)) *MockPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockPinger_Ping_Call) Return(_a0 bool) *MockPinger_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPinger_Ping_Call) RunAndReturn(run func(string, time.Duration) bool) *MockPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinger creates a new instance of MockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinger {
	mock := &MockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
