// Code generated by mockery v2.53.6. DO NOT EDIT.

package mock

import (
	context "context"
	domain "sms-reporting/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockReportingRepository is an autogenerated mock type for the ReportingRepository type
type MockReportingRepository struct {
	mock.Mock
}

type MockReportingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportingRepository) EXPECT() *MockReportingRepository_Expecter {
	return &MockReportingRepository_Expecter{mock: &_m.Mock}
}

// CreateReportRequest provides a mock function with given fields: ctx, req
func (_m *MockReportingRepository) CreateReportRequest(ctx context.Context, req *domain.ReportRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateReportRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReportRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportingRepository_CreateReportRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReportRequest'
type MockReportingRepository_CreateReportRequest_Call struct {
	*mock.Call
}

// CreateReportRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.ReportRequest
func (_e *MockReportingRepository_Expecter) CreateReportRequest(ctx interface{}, req interface{}) *MockReportingRepository_CreateReportRequest_Call {
	return &MockReportingRepository_CreateReportRequest_Call{Call: _e.mock.On("CreateReportRequest", ctx, req)}
}

func (_c *MockReportingRepository_CreateReportRequest_Call) Run(run func(ctx context.Context, req *domain.ReportRequest)) *MockReportingRepository_CreateReportRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ReportRequest))
	})
	return _c
}

func (_c *MockReportingRepository_CreateReportRequest_Call) Return(_a0 error) *MockReportingRepository_CreateReportRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportingRepository_CreateReportRequest_Call) RunAndReturn(run func(context.Context, *domain.ReportRequest) error) *MockReportingRepository_CreateReportRequest_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReportingServer provides a mock function with given fields: ctx, serverID
func (_m *MockReportingRepository) DeleteReportingServer(ctx context.Context, serverID string) error {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReportingServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportingRepository_DeleteReportingServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReportingServer'
type MockReportingRepository_DeleteReportingServer_Call struct {
	*mock.Call
}

// DeleteReportingServer is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
func (_e *MockReportingRepository_Expecter) DeleteReportingServer(ctx interface{}, serverID interface{}) *MockReportingRepository_DeleteReportingServer_Call {
	return &MockReportingRepository_DeleteReportingServer_Call{Call: _e.mock.On("DeleteReportingServer", ctx, serverID)}
}

func (_c *MockReportingRepository_DeleteReportingServer_Call) Run(run func(ctx context.Context, serverID string)) *MockReportingRepository_DeleteReportingServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReportingRepository_DeleteReportingServer_Call) Return(_a0 error) *MockReportingRepository_DeleteReportingServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportingRepository_DeleteReportingServer_Call) RunAndReturn(run func(context.Context, string) error) *MockReportingRepository_DeleteReportingServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetServerCountByStatus provides a mock function with given fields: ctx, status
func (_m *MockReportingRepository) GetServerCountByStatus(ctx context.Context, status string) (int64, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetServerCountByStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportingRepository_GetServerCountByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServerCountByStatus'
type MockReportingRepository_GetServerCountByStatus_Call struct {
	*mock.Call
}

// GetServerCountByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *MockReportingRepository_Expecter) GetServerCountByStatus(ctx interface{}, status interface{}) *MockReportingRepository_GetServerCountByStatus_Call {
	return &MockReportingRepository_GetServerCountByStatus_Call{Call: _e.mock.On("GetServerCountByStatus", ctx, status)}
}

func (_c *MockReportingRepository_GetServerCountByStatus_Call) Run(run func(ctx context.Context, status string)) *MockReportingRepository_GetServerCountByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReportingRepository_GetServerCountByStatus_Call) Return(_a0 int64, _a1 error) *MockReportingRepository_GetServerCountByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportingRepository_GetServerCountByStatus_Call) RunAndReturn(run func(context.Context, string) (int64, error)) *MockReportingRepository_GetServerCountByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReportStatus provides a mock function with given fields: ctx, id, status
func (_m *MockReportingRepository) UpdateReportStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReportStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportingRepository_UpdateReportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReportStatus'
type MockReportingRepository_UpdateReportStatus_Call struct {
	*mock.Call
}

// UpdateReportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
func (_e *MockReportingRepository_Expecter) UpdateReportStatus(ctx interface{}, id interface{}, status interface{}) *MockReportingRepository_UpdateReportStatus_Call {
	return &MockReportingRepository_UpdateReportStatus_Call{Call: _e.mock.On("UpdateReportStatus", ctx, id, status)}
}

func (_c *MockReportingRepository_UpdateReportStatus_Call) Run(run func(ctx context.Context, id string, status string)) *MockReportingRepository_UpdateReportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockReportingRepository_UpdateReportStatus_Call) Return(_a0 error) *MockReportingRepository_UpdateReportStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportingRepository_UpdateReportStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockReportingRepository_UpdateReportStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReportingServerStatus provides a mock function with given fields: ctx, serverID, status
func (_m *MockReportingRepository) UpdateReportingServerStatus(ctx context.Context, serverID string, status string) error {
	ret := _m.Called(ctx, serverID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReportingServerStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, serverID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportingRepository_UpdateReportingServerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReportingServerStatus'
type MockReportingRepository_UpdateReportingServerStatus_Call struct {
	*mock.Call
}

// UpdateReportingServerStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
//   - status string
func (_e *MockReportingRepository_Expecter) UpdateReportingServerStatus(ctx interface{}, serverID interface{}, status interface{}) *MockReportingRepository_UpdateReportingServerStatus_Call {
	return &MockReportingRepository_UpdateReportingServerStatus_Call{Call: _e.mock.On("UpdateReportingServerStatus", ctx, serverID, status)}
}

func (_c *MockReportingRepository_UpdateReportingServerStatus_Call) Run(run func(ctx context.Context, serverID string, status string)) *MockReportingRepository_UpdateReportingServerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockReportingRepository_UpdateReportingServerStatus_Call) Return(_a0 error) *MockReportingRepository_UpdateReportingServerStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportingRepository_UpdateReportingServerStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockReportingRepository_UpdateReportingServerStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertReportingServer provides a mock function with given fields: ctx, server
func (_m *MockReportingRepository) UpsertReportingServer(ctx context.Context, server *domain.ReportingServer) error {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for UpsertReportingServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ReportingServer) error); ok {
		r0 = rf(ctx, server)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportingRepository_UpsertReportingServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertReportingServer'
type MockReportingRepository_UpsertReportingServer_Call struct {
	*mock.Call
}

// UpsertReportingServer is a helper method to define mock.On call
//   - ctx context.Context
//   - server *domain.ReportingServer
func (_e *MockReportingRepository_Expecter) UpsertReportingServer(ctx interface{}, server interface{}) *MockReportingRepository_UpsertReportingServer_Call {
	return &MockReportingRepository_UpsertReportingServer_Call{Call: _e.mock.On("UpsertReportingServer", ctx, server)}
}

func (_c *MockReportingRepository_UpsertReportingServer_Call) Run(run func(ctx context.Context, server *domain.ReportingServer)) *MockReportingRepository_UpsertReportingServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ReportingServer))
	})
	return _c
}

func (_c *MockReportingRepository_UpsertReportingServer_Call) Return(_a0 error) *MockReportingRepository_UpsertReportingServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportingRepository_UpsertReportingServer_Call) RunAndReturn(run func(context.Context, *domain.ReportingServer) error) *MockReportingRepository_UpsertReportingServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportingRepository creates a new instance of MockReportingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportingRepository {
	mock := &MockReportingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
